name: Release

env:
  DO_NOT_TRACK: 1

on:
  push:
    tags:
      - "@osdk/foundry@*"
      - "@osdk/gotham@*"
      - "@osdk/shared.net.platformapi@*"

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build & lint
        run: pnpm prePublish

      - name: Publish packages
        run: pnpm publish --no-git-checks -r --report-summary --access restricted

      - name: Save publish data
        uses: actions/upload-artifact@v5
        with:
          name: published-packages
          path: pnpm-publish-summary.json
